### ISSUE TITLE
disable CamEwarn UUID

### ISSUE THREAD

**Issue by Thyda-Eng** [ilabsea/zero-reporting#77]

**Comment by kakada** [comment]
When hub setting is disabled then
  1. location hierarchy list should be disabled CamEwarn UUID
  2. create a new location(PHD, OD, HC) should be disabled CamEwarn UUID
  3. download location & user as CSV should be disabled CamEwarn UUID column

![hub-setting](https://user-images.githubusercontent.com/745429/31814953-5ee3a9d8-b5b5-11e7-8905-43250ab9499a.png)
![location-camewarn-uuid](https://user-images.githubusercontent.com/745429/31814954-5f27c992-b5b5-11e7-8a6b-f6ffe3f1bc80.png)
![new-location-camewarn-uuid](https://user-images.githubusercontent.com/745429/31814955-5f605fbe-b5b5-11e7-95f1-1526a344f5e4.png)
![csv-camewarn-uuid](https://user-images.githubusercontent.com/745429/31814952-5e9d1edc-b5b5-11e7-872c-74ac3475a51b.png)
